name: "Build SGSI"

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: 'https://hugeota.d.miui.com/21.5.31/miui_TUCANA_21.5.31_cb42ec9bed_11.0.zip'
      OS_TYPE:
        description: 'OS_TYPE'
        required: true
        default: 'miui'
      REPACK_NAME:
        description: 'REPACK_NAME'
        required: true
        default: 'SGSI.zip'
jobs:
  sgsi:
    name: Ready For env
    runs-on: ubuntu-latest
    steps:
    - name: Ready For env
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install git python3 python
        sudo apt install aria2
        git clone --recurse-submodules https://github.com/xiaoxindada/SGSI-build-tool.git -b 11 SGSI-build-tool-11
        cd SGSI-build-tool-11
        sudo bash ./setup.sh
        
    - name: Download ROM
      run: |
        cd ${{ github.workspace }}/SGSI-build-tool-11/
        mkdir tmp
        cd tmp
        aria2c -x 16 --check-certificate=false ${{ github.event.inputs.ROM_URL }}

    - name: Start Build
      run: |
        cd ${{ github.workspace }}/SGSI-build-tool-11/
        sudo bash ./make.sh AB << EOF

        n
        n
        ${{ github.event.inputs.OS_TYPE }}
        y
