name: "Build SGSI"

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: 'https://bigota.d.miui.com/22.3.2/miui_TUCANA_22.3.2_e735556b82_11.0.zip'
      OS_TYPE:
        description: 'OS_TYPE'
        required: true
        default: 'miui'
      REPACK_NAME:
        description: 'REPACK_NAME'
        required: true
        default: 'SGSI.zip'

jobs:
  sgsi:
    name: Ready For env
    runs-on: ubuntu-latest
    steps:
    - name: Ready For env
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install git python3 python
        sudo apt install aria2
        git clone --recurse-submodules https://github.com/xiaoxindada/SGSI-build-tool.git -b 11 SGSI-build-tool-11
        cd SGSI-build-tool-11
        sudo bash ./setup.sh
        
    - name: Download ROM
      run: |
        cd ${{ github.workspace }}/SGSI-build-tool-11/
        mkdir tmp
        cd tmp
        aria2c -x 16 --check-certificate=false ${{ github.event.inputs.ROM_URL }}

    - name: Start Build
      run: |
        cd ${{ github.workspace }}/SGSI-build-tool-11/
        sudo bash ./make.sh AB << EOF

        n
        n
        ${{ github.event.inputs.OS_TYPE }}
        y

    - name: Zip Output
      run: |
        sudo apt install zip
        cd ${{ github.workspace }}/SGSI-build-tool-11/
        mkdir zip_out
        zip -q -r ./zip_out/SGSI.zip ./SGSI
        curl -sL https://git.io/file-transfer | sh
        ./transfer --silent gof ./zip_out/

    - name: Packing(AB)...
      run: |
        cd $GITHUB_WORKSPACE/Tool-SGSI-build
        pwd
        zip -r AB_${{ github.event.inputs.REPACK_NAME }} SGSI/*
        ls "AB_${{ github.event.inputs.REPACK_NAME }}"
        echo "--------------------------------------"
        ls
        echo "--------------------------------------"
        mkdir upload_ab
        echo "--------------------------------------"
        ls upload_ab
        echo "--------------------------------------"
        if [ $(ls -l AB_${{ github.event.inputs.REPACK_NAME }} | awk '{print $5}') -gt 2147483647 ]; then tar cvzpf - AB_${{ github.event.inputs.REPACK_NAME }} | split -d -b 1024m - upload_ab/AB_${{ github.event.inputs.REPACK_NAME }}; else mv AB_${{ github.event.inputs.REPACK_NAME }} upload_ab/AB_${{ github.event.inputs.REPACK_NAME }}; fi
        echo "--------------------------------------"
        ls upload_ab
        echo "--------------------------------------"
